springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    path: /api-test
    enabled: true
  paths-to-match:
    - /api/**
  api-docs:
    enabled: true

spring:
  application:
    name: intro
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8080
